package com.example.domain;

public class Sample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.id
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.name
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.value
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.id
     *
     * @return the value of sample.id
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.id
     *
     * @param id the value for sample.id
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.name
     *
     * @return the value of sample.name
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.name
     *
     * @param name the value for sample.name
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.value
     *
     * @return the value of sample.value
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.value
     *
     * @param value the value for sample.value
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}