package com.example.mapper;

import com.example.domain.Sample;
import com.example.domain.SampleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SampleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    int countByExample(SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    int deleteByExample(SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    int insert(Sample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    int insertSelective(Sample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    List<Sample> selectByExampleWithBLOBs(SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    List<Sample> selectByExample(SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    Sample selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    int updateByExampleSelective(@Param("record") Sample record, @Param("example") SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") Sample record, @Param("example") SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    int updateByExample(@Param("record") Sample record, @Param("example") SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    int updateByPrimaryKeySelective(Sample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Sun Jan 03 22:40:29 JST 2021
     */
    int updateByPrimaryKeyWithBLOBs(Sample record);
}